/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethodTotals = IDL.Record({
  'trf' : IDL.Nat,
  'tunai' : IDL.Nat,
  'dana' : IDL.Nat,
  'qris' : IDL.Nat,
});
export const DashboardSummary = IDL.Record({
  'paymentMethodTotals' : PaymentMethodTotals,
  'todayRevenue' : IDL.Nat,
  'totalQuantitySold' : IDL.Nat,
});
export const Time = IDL.Int;
export const CashTransaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'nominalAmount' : IDL.Nat,
  'date' : IDL.Text,
  'item' : IDL.Text,
  'createdAt' : Time,
  'picName' : IDL.Text,
  'quantity' : IDL.Int,
  'category' : IDL.Text,
  'monthYear' : IDL.Text,
});
export const InventoryReportEntry = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : Time,
  'itemName' : IDL.Text,
  'itemSize' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'reject' : IDL.Nat,
  'minimumStock' : IDL.Nat,
  'initialStock' : IDL.Nat,
  'size' : IDL.Text,
  'unit' : IDL.Text,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
  'finalStock' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'hpp' : IDL.Nat,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'category' : IDL.Text,
  'salePrice' : IDL.Nat,
  'image' : ExternalBlob,
});
export const PaymentMethod = IDL.Variant({
  'trf' : IDL.Null,
  'tunai' : IDL.Null,
  'dana' : IDL.Null,
  'qris' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'cogs' : IDL.Nat,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const SaleRecord = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'totalTax' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(SaleItem),
  'amount' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCashTransaction' : IDL.Func(
      [IDL.Nat, TransactionType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addExpenseRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addInventoryItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'adjustInventoryStock' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCashTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSale' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'fetchDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getAllCashTransactions' : IDL.Func(
      [],
      [IDL.Vec(CashTransaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCashBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCashTransactionsByDate' : IDL.Func(
      [Time, Time],
      [IDL.Vec(CashTransaction)],
      ['query'],
    ),
  'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'getInventoryReports' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(InventoryReportEntry)],
      ['query'],
    ),
  'getInventoryUsageStats' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Time), IDL.Opt(Time)],
      [IDL.Nat],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInventoryLow' : IDL.Func([], [IDL.Bool], ['query']),
  'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'querySales' : IDL.Func([Time, Time], [IDL.Vec(SaleRecord)], ['query']),
  'recordSale' : IDL.Func(
      [IDL.Vec(SaleItem), PaymentMethod, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCashTransaction' : IDL.Func(
      [IDL.Nat, IDL.Nat, TransactionType, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
  'updateSale' : IDL.Func(
      [IDL.Nat, IDL.Vec(SaleItem), PaymentMethod, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethodTotals = IDL.Record({
    'trf' : IDL.Nat,
    'tunai' : IDL.Nat,
    'dana' : IDL.Nat,
    'qris' : IDL.Nat,
  });
  const DashboardSummary = IDL.Record({
    'paymentMethodTotals' : PaymentMethodTotals,
    'todayRevenue' : IDL.Nat,
    'totalQuantitySold' : IDL.Nat,
  });
  const Time = IDL.Int;
  const CashTransaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'nominalAmount' : IDL.Nat,
    'date' : IDL.Text,
    'item' : IDL.Text,
    'createdAt' : Time,
    'picName' : IDL.Text,
    'quantity' : IDL.Int,
    'category' : IDL.Text,
    'monthYear' : IDL.Text,
  });
  const InventoryReportEntry = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : Time,
    'itemName' : IDL.Text,
    'itemSize' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'reject' : IDL.Nat,
    'minimumStock' : IDL.Nat,
    'initialStock' : IDL.Nat,
    'size' : IDL.Text,
    'unit' : IDL.Text,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
    'finalStock' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'hpp' : IDL.Nat,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'category' : IDL.Text,
    'salePrice' : IDL.Nat,
    'image' : ExternalBlob,
  });
  const PaymentMethod = IDL.Variant({
    'trf' : IDL.Null,
    'tunai' : IDL.Null,
    'dana' : IDL.Null,
    'qris' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'cogs' : IDL.Nat,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const SaleRecord = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'totalTax' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(SaleItem),
    'amount' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCashTransaction' : IDL.Func(
        [IDL.Nat, TransactionType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addExpenseRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addInventoryItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'adjustInventoryStock' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCashTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSale' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'fetchDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getAllCashTransactions' : IDL.Func(
        [],
        [IDL.Vec(CashTransaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCashBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCashTransactionsByDate' : IDL.Func(
        [Time, Time],
        [IDL.Vec(CashTransaction)],
        ['query'],
      ),
    'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'getInventoryReports' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(InventoryReportEntry)],
        ['query'],
      ),
    'getInventoryUsageStats' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Time), IDL.Opt(Time)],
        [IDL.Nat],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInventoryLow' : IDL.Func([], [IDL.Bool], ['query']),
    'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'querySales' : IDL.Func([Time, Time], [IDL.Vec(SaleRecord)], ['query']),
    'recordSale' : IDL.Func(
        [IDL.Vec(SaleItem), PaymentMethod, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCashTransaction' : IDL.Func(
        [IDL.Nat, IDL.Nat, TransactionType, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
    'updateSale' : IDL.Func(
        [IDL.Nat, IDL.Vec(SaleItem), PaymentMethod, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };