/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CashTransaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface DashboardSummary {
  'paymentMethodTotals' : PaymentMethodTotals,
  'todayRevenue' : bigint,
  'totalQuantitySold' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface InventoryItem {
  'id' : bigint,
  'reject' : bigint,
  'minimumStock' : bigint,
  'initialStock' : bigint,
  'size' : string,
  'unit' : string,
  'itemName' : string,
  'category' : string,
  'finalStock' : bigint,
}
export interface InventoryReportEntry {
  'description' : string,
  'timestamp' : Time,
  'itemName' : string,
  'itemSize' : string,
  'quantity' : bigint,
}
export type PaymentMethod = { 'trf' : null } |
  { 'tunai' : null } |
  { 'dana' : null } |
  { 'qris' : null };
export interface PaymentMethodTotals {
  'trf' : bigint,
  'tunai' : bigint,
  'dana' : bigint,
  'qris' : bigint,
}
export interface Product {
  'id' : bigint,
  'hpp' : bigint,
  'name' : string,
  'size' : string,
  'category' : string,
  'salePrice' : bigint,
  'image' : ExternalBlob,
}
export interface SaleItem {
  'cogs' : bigint,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface SaleRecord {
  'id' : bigint,
  'paymentMethod' : PaymentMethod,
  'totalTax' : bigint,
  'timestamp' : Time,
  'items' : Array<SaleItem>,
  'amount' : bigint,
  'totalQuantity' : bigint,
}
export type Time = bigint;
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCashTransaction' : ActorMethod<[bigint, TransactionType, string], bigint>,
  'addInventoryItem' : ActorMethod<
    [string, string, string, string, bigint, bigint, bigint, bigint],
    [] | [bigint]
  >,
  'addProduct' : ActorMethod<
    [string, string, string, bigint, bigint, ExternalBlob],
    bigint
  >,
  'adjustInventoryStock' : ActorMethod<
    [bigint, bigint, boolean, string],
    boolean
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCashTransaction' : ActorMethod<[bigint], boolean>,
  'deleteSale' : ActorMethod<[bigint], boolean>,
  'fetchDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getAllCashTransactions' : ActorMethod<[], Array<CashTransaction>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashBalance' : ActorMethod<[], bigint>,
  'getCashTransactionsByDate' : ActorMethod<
    [Time, Time],
    Array<CashTransaction>
  >,
  'getInventoryReports' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<InventoryReportEntry>
  >,
  'getInventoryUsageStats' : ActorMethod<
    [[] | [string], [] | [string], [] | [Time], [] | [Time]],
    bigint
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isInventoryLow' : ActorMethod<[], boolean>,
  'listInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'querySales' : ActorMethod<[Time, Time], Array<SaleRecord>>,
  'recordSale' : ActorMethod<[Array<SaleItem>, PaymentMethod, bigint], bigint>,
  'updateCashTransaction' : ActorMethod<
    [bigint, bigint, TransactionType, string],
    boolean
  >,
  'updateInventoryItem' : ActorMethod<
    [bigint, string, string, string, string, bigint, bigint, bigint, bigint],
    boolean
  >,
  'updateSale' : ActorMethod<
    [bigint, Array<SaleItem>, PaymentMethod, bigint],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];